### ISSUE TITLE
Unable to run when using useLocalStorage (Vite)

### ISSUE THREAD

**Issue by RoyRao2333** [justinmahar/react-storage-complete#1]
Just got this error and my project crashed:

<img width="735" alt="image" src="https://user-images.githubusercontent.com/31413093/220816590-90f6d7cf-6bdf-4090-9dc7-030664c40f50.png">

My code:

```ts
const userTokenStorageKey = 'USER_TOKEN_STORAGE_KEY';
// Remove this and the project can run properly.
const [, setUserToken] = useLocalStorage<string>(userTokenStorageKey);

const onFinish = useCallback(
    async (values) => {
      // ......
      if (success) {
        if (data.token) {
          setUserToken(data.token);
        }
      }
    },
    [setUserToken],
  );
```

**Comment by justinmahar** [comment]
Is this still an issue? I've been using this library in multiple projects with no issues like this. The code itself for the library is just a hook that's being exported, nothing fancy. Was this error during development, or after your app was built, bundled and deployed? Are you using any particular framework for your app?

**Comment by RoyRao2333** [comment]
@justinmahar 

Thanks for the reply!

So my project is basically written with Vite + React, and nothing particular I guess. This issue is happening during dev, which literally prevents me from running my project.

**Comment by justinmahar** [comment]
Not sure if it's related, but I just ran into SSR issues using localStorage in production. Just shipped a new version of the library to fix that and SSR issues are history.

To get the latest:

```
npm i react-storage-complete@latest
```

**Comment by RoyRao2333** [comment]
@justinmahar 

Thanks for the effort, but it's still no luck with the latest version... 😢

<img width="731" alt="image" src="https://user-images.githubusercontent.com/31413093/223029036-f4154541-c6cd-4eb1-844a-1f372860e5b4.png">

Don't know if this issue is related with Vite or React Router?

**Comment by justinmahar** [comment]
Closing for now

**Comment by joe-noumena** [comment]
I am getting the same thing on a Vite project react-storage-complete.js?v=55b96d91:420 Uncaught TypeError: events_1.default is not a constructor

    at node_modules/react-storage-complete/dist/hooks/useBrowserStorage.js (react-storage-complete.js?v=55b96d91:420:35)
    at __require2 (chunk-AUZ3RYOM.js?v=55b96d91:18:50)
    at node_modules/react-storage-complete/dist/index.js (react-storage-complete.js?v=55b96d91:502:18)
    at __require2 (chunk-AUZ3RYOM.js?v=55b96d91:18:50)
    at react-storage-complete.js?v=55b96d91:507:16

Works fine on a webpack project.

**Comment by RoyRao2333** [comment]
@joe-noumena 

Thanks for the clarification! So it seems a Vite issue then? @justinmahar

**Comment by JoeGaffney** [comment]
@RoyRao2333 yeah it seems to be maybe esm issue. 

I am trying https://www.npmjs.com/package/use-local-storage-state on the vite project which seems to work. Although not as many features as this package

**Comment by justinmahar** [comment]
Do either of you have any idea what the heck might be going on with this? I'd love to fix this. I'm bundling 10+ other libraries for npm the exact same way as this one

**Comment by justinmahar** [comment]
Leaving this here for later, but I think updating the tsconfig for this project might be a start

use-storage-complete tsconfig (this project, working with webpack, issues with Vite)
- https://github.com/justinmahar/react-storage-complete/blob/master/tsconfig.json

use-local-storage-state tsconfig (works with Vite)
- https://github.com/astoilkov/use-local-storage-state/blob/main/tsconfig.json

notes
- https://medium.com/dazn-tech/publishing-npm-packages-as-native-es-modules-41ffbc0a9dea

I'm using cjs, maybe I need to bump that up to esm for this project and all others

**Comment by cod3rboy** [comment]
Facing the same issue on vite+react+ts project.

**Comment by justinmahar** [comment]
I ran into some React hydration issues in a Gatsby project (stoicdevotional.com) using this library with the latest React+Gatsby, and I believe I found and fixed the issue as a result. Storage is now initialized after an effect completes. This solved the issues in my project, might do the same for yours. Let us know if you do end up trying it out and it works for you.

To get the latest version:

```
npm i react-storage-complete@latest
```

**Comment by Foorack** [comment]
Still facing this error message with version `1.1.13`. TypeScript+React+Vite.

```js
useBrowserStorage.js:158  Uncaught TypeError: events_1.default is not a constructor
    at node_modules/react-storage-complete/dist/hooks/useBrowserStorage.js (useBrowserStorage.js:158:31)
    at __require (chunk-V4OQ3NZ2.js:11:50)
    at node_modules/react-storage-complete/dist/index.js (index.js:17:14)
    at __require (chunk-V4OQ3NZ2.js:11:50)
    at index.js:19:59
node_modules/react-storage-complete/dist/hooks/useBrowserStorage.js @ useBrowserStorage.js:158
__require @ chunk-V4OQ3NZ2.js:11
node_modules/react-storage-complete/dist/index.js @ index.js:17
__require @ chunk-V4OQ3NZ2.js:11
(anonymous) @ index.js:19
```
